<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
	public function status($date, $showTime)
	{
		return $this->createQueryBuilder('b')
            ->select('count(b.id)')
            ->andWhere("b.date = :date")
            ->andWhere("b.showTime = :showTime")
            ->setParameter("date", $date)
            ->setParameter("showTime", $showTime)
            ->getQuery()
            ->getSingleScalarResult();
	}	
}
